set(_CATKIN_CURRENT_PACKAGE "color_tracking")
set(color_tracking_VERSION "0.0.0")
set(color_tracking_MAINTAINER "ubuntu <ubuntu@todo.todo>")
set(color_tracking_PACKAGE_FORMAT "1")
set(color_tracking_BUILD_DEPENDS "cv_bridge" "image_transport" "opencv3" "roscpp")
set(color_tracking_BUILD_EXPORT_DEPENDS "cv_bridge" "image_transport" "opencv3" "roscpp")
set(color_tracking_BUILDTOOL_DEPENDS "catkin")
set(color_tracking_BUILDTOOL_EXPORT_DEPENDS )
set(color_tracking_EXEC_DEPENDS "cv_bridge" "image_transport" "opencv3" "roscpp")
set(color_tracking_RUN_DEPENDS "cv_bridge" "image_transport" "opencv3" "roscpp")
set(color_tracking_TEST_DEPENDS )
set(color_tracking_DOC_DEPENDS )
set(color_tracking_URL_WEBSITE "")
set(color_tracking_URL_BUGTRACKER "")
set(color_tracking_URL_REPOSITORY "")
set(color_tracking_DEPRECATED "")